### ISSUE TITLE
LICENSE file difficult to view on a Mac

### ISSUE THREAD

**Issue by tempelmann** [vashchenko/smjobbless#1]
That's because it's by default seen as an executable. If you'd renamed it into "LICENSE.txt", it can be more easily opened.

**Comment by aronskaya** [comment]
Hi, @tempelmann!
Thanks for the interest in the project. Hope it will be helpful to you.

This file is generated automatically when one creates a repository on GitHub and chooses the license type, so you'll probably see lots of repositories with the same license naming. 

Although I decided to add an extension for convenience.

**Comment by tempelmann** [comment]
Oh, that's why I see that badly named file so often. Thanks for making it better. I will try to contact github and raise this little "issue" with them directly.
